baseURL = 'https://preview.kasniaproject.us.kg/'
languageCode = 'en-us'
title = 'Kasnia Project'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats.novelasJSON]
  mediaType = "application/json"
  baseName = "novelas"
  isPlainText = true
  notAlternative = true
  