languageCode = "es"
title = "Kasnia Project"

#Para minificaci√≥n de archivos
[minify]
  disableHTML = false
  disableJSON = false
  disableXML = false
  disableSVG = false

#Para poner html en markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

#Para generar json
[outputFormats.novelasJSON]
  mediaType = "application/json"
  baseName = "novelas"
  isPlainText = true
  notAlternative = true
  